version: '3.7'
services:
  app:
    image: app-cointaro
    restart: unless-stopped
    environment:
       - MONGODB_URL=${MONGODB_URL}
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynetwork  

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork   

volumes:
  mongo-data:

networks:
  mynetwork: