version: '3.7'
services:
  app:
    image: app-cointaro
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cointaro
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
